#!/usr/bin/env bash
set -euo pipefail

username="Neelima-16"
readme="README.md"
api_url="https://api.github.com/users/${username}/repos?per_page=100&sort=updated"

curl_args=(
  --fail
  --silent
  --show-error
  --header "X-GitHub-Api-Version: 2022-11-28"
)

if [[ -n "${GITHUB_TOKEN:-}" ]]; then
  curl_args+=(--header "Authorization: Bearer ${GITHUB_TOKEN}")
fi

repos="$(curl "${curl_args[@]}" "$api_url")"

table="$(jq -r --arg username "$username" '
  [ .[] | select(.fork | not) ]
  | to_entries[]
  | (.value.description // "—" | gsub("[\\r\\n]+"; " ") | gsub("\\|"; "\\\\|")) as $description
  | "| \(.key + 1) | [\(.value.name)](https://github.com/\($username)/\(.value.name)) | \($description) | `\(.value.language // "—")` | \(.value.stargazers_count) |"
' <<< "$repos")"

replacement="<!-- PROJECTS:START -->
<!-- This table is generated by .github/workflows/update-projects.yml. -->
| # | Project | Description | Stack | Stars |
|:---:|:---|:---|:---|:---:|
${table}
<!-- PROJECTS:END -->"

replacement_file="$(mktemp)"
temp_file="$(mktemp)"
printf '%s\n' "$replacement" > "$replacement_file"

awk -v replacement_file="$replacement_file" '
  /<!-- PROJECTS:START -->/ {
    while ((getline line < replacement_file) > 0) print line
    close(replacement_file)
    skip = 1
    next
  }
  /<!-- PROJECTS:END -->/ { skip = 0; next }
  !skip { print }
' "$readme" > "$temp_file"

rm "$replacement_file"
mv "$temp_file" "$readme"
